// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RW8yz5Ko6oR8LK9Zi6mRm7nmPKAsIpQ',
    appId: '1:424164250930:web:d443d5af51d0f564fd732b',
    messagingSenderId: '424164250930',
    projectId: 'kopilab-d2813',
    authDomain: 'kopilab-d2813.firebaseapp.com',
    databaseURL: 'https://kopilab-d2813-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kopilab-d2813.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9mguJskw2aMJEdkx6yp_qARAGUBGj9c',
    appId: '1:424164250930:android:1337c4d8659b7a0cfd732b',
    messagingSenderId: '424164250930',
    projectId: 'kopilab-d2813',
    databaseURL: 'https://kopilab-d2813-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kopilab-d2813.appspot.com',
  );
}
